services:
  api-server:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw
      - ../dbt_workflow/datawarehouse/:/usr/local/airflow/datawarehouse/:rw
    networks:
    - minha_network_airflow

  scheduler:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw
      - ../dbt_workflow/datawarehouse/:/usr/local/airflow/datawarehouse/:rw
    networks:
    - minha_network_airflow

  triggerer:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw
      - ../dbt_workflow/datawarehouse/:/usr/local/airflow/datawarehouse/:rw
    networks:
    - minha_network_airflow

  dag-processor:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw
      - ../dbt_workflow/datawarehouse/:/usr/local/airflow/datawarehouse/:rw
    networks:
    - minha_network_airflow

networks:
  minha_network_airflow:
    driver: bridge
    name: airflow_network  