version: "3.1"

services:
  scheduler:
    volumes:
      - ../dbt_workflow/:/usr/local/airflow/include/dbt_workflow/:rw
      #- ./dags/dbt/dbt_workflow:/usr/local/airflow/include/dbt_workflow/:rw
      - ../../data/:/usr/local/airflow/include/data/:rw
      - ../../utils/ingestao.py:/usr/local/airflow/include/ingestao.py:ro


  # webserver:
  #   volumes:
  #     - ../dbt_workflow/:/usr/local/airflow/dbt:rw

  # triggerer:
  #   volumes:
  #     - ../dbt_workflow/:/usr/local/airflow/dbt:rw


