version: "3.1"

services:
  api-server:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw

  scheduler:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw

  triggerer:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw

  dag-processor:
    volumes:
      - ../dbt_workflow:/usr/local/airflow/include/dbt_workflow:rw
      - ../../data/:/usr/local/airflow/include/data:rw
      - ../../utils/ingestao_minio.py:/usr/local/airflow/ingestao_minio.py:rw



